%Restricciones
padre(cristian,arturo).
padre(mauricio,esteban).
padre(luis,oscar).
padre(arturo,pedro).
padre(pedro,mauricio).
padre(pedro,luis).
hermano(mauricio,luis).
hermano(arturo,blanca).
hermano(milena,tatiana).
madre(lisa,arturo).
madre(lisa,blanca).
madre(tatiana,oscar).
madre(milena,esteban).
mujer(milena).
mujer(tatiana).
mujer(lisa).
mujer(blanca).
-mujer(cristian).
-mujer(arturo).
-mujer(mauricio).
-mujer(esteban).
-mujer(luis).
-mujer(oscar).
-mujer(pedro).
%Relaciones
nieto(X,Y):-padre(Y,C),padre(C,X),-mujer(Y).
tia(X,Y):-(padre(C,Y);madre(C,Y)),hermano(C,X),mujer(X).
primohermano(X,Y):-(padre(C,X);madre(C,X)),(padre(Z,Y);madre(Z,Y)),hermano(C,Z).
abuelapaterna(X,Y):-padre(C,Y),-mujer(C),madre(X,C).
bisabuelo(X,Y):-padre(X,C),(padre(C,Z);madre(C,Z)),(padre(Z,Y);madre(Z,Y)),-mujer(X).
